[package]
name = "chip-8-rust"
version = "0.1.0"
authors = ["Leo Huang <leo.h@wbstech.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
ux = "0.1.3"
